version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000  # Usar nombre del servicio

  backend:
    build: ./backend
    expose:
      - "5000"
    env_file:
      - .env