version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=tu-ip-ec2
      - DB_USER=postgres
      - DB_PASSWORD=tu-password
      - DB_NAME=sales
      - WEATHER_API_KEY=tu-api-key-clima
      - COLOR_API_ENABLED=true